//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login_game.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLoginGame")]
  public partial class CSLoginGame : global::ProtoBuf.IExtensible
  {
    public CSLoginGame() {}
    

    private string _m_nAccount = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"m_nAccount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string m_nAccount
    {
      get { return _m_nAccount; }
      set { _m_nAccount = value; }
    }

    private string _m_nPassword = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"m_nPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string m_nPassword
    {
      get { return _m_nPassword; }
      set { _m_nPassword = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}